### ISSUE TITLE
Any prompt requiring a webpage retrieval doesn’t work. 

### ISSUE THREAD

**Issue by courtsimas** [f/awesome-chatgpt-prompts#143]
Acts as browser no longer works. It’s gotten stricter on fetching webpages, no matter how the instructions are worded; it won’t fetch webpages.

**Comment by matthewdeanmartin** [comment]
I'm sure you meant "hallicinate" instead of "fetch", but I'm going to write it anyhow...

It can only hallucinate a webpage. It often will say 404 instead of "As a LLM, I can't do that" and it takes a URL as peculiar question, e.g. "https://google.com?who is julius caesar" it will generate a page with plausible HTML wrapped around the text to the question "who is julius caesar" which will be heavily influence by the wikipedia article, of course.

If I give it a URL of http://asdfsaddf.com?ADFASWF there isn't an inferable question in that URL so it will balk.

**Comment by courtsimas** [comment]
Well I’m saying i copied the prompt verbatim and had it complain.
