### ISSUE TITLE
Automate readme using github workflow

### ISSUE THREAD

**Issue by Vazno** [f/awesome-chatgpt-prompts#275]
What do I mean?
We can create workflow to automatically update readme using prompts.csv, it will help to reduce problems with new prompts being merged into main, and make life easier.

It will work like this:
User opens PR (Adds prompt to the prompts.csv)
Merging PR
Workflow adds that prompt to the README.md

**Comment by Vazno** [comment]
You can assign this to me

**Comment by dogagenc** [comment]
I was here to open a similar issue. 

I also suggest using placeholders instead of embedding arguments and example prompts. 

Example: 
```
title: Linux Terminal
prompt: `i want you to act as a linux terminal. I will type commands...curly brackets {like this}. my first command is $0`
args: ['pwd']
```

See how we use $0 (at the end of prompt) as argument placeholder. This gives us more flexibility using prompts for third party apps. 

Github actions also generate a json file out of csv. 
Another idea would be the split prompts into their own files inside a `prompts` folder.

**Comment by Vazno** [comment]
> I also suggest using placeholders instead of embedding arguments and example prompts.

That's smart!

> Github actions also generate a json file out of csv.

That's smart too!

> Another idea would be the split prompts into their own files inside a prompts folder.

I think csv, json will be easier to store, and to access for third party apps

**Comment by dogagenc** [comment]
@Vazno Splitting prompts into their own files just for scalability, maintenance, linting, etc... JSON and CSV will be generated by Github Actions again.

**Comment by dogagenc** [comment]
Once we have the json file, it will be easier to create a Github page using some templating system with embedded search. 

cc: @f This project is here to scale. Thanks for your efforts! 🙏
