### ISSUE TITLE
ChatGTP not able to write code?

### ISSUE THREAD

**Issue by lucianotonet** [f/awesome-chatgpt-prompts#304]
Trying to follow [Act as a Senior Developer](https://github.com/f/awesome-chatgpt-prompts#act-as-a-senior-frontend-developer)
![image](https://user-images.githubusercontent.com/2693019/214955083-09c4a4fa-ff60-4fee-8abd-964a96aa7429.png)

**Comment by lucianotonet** [comment]
@abilzerian

Before I close this, can you recommend some tool to create/edit prompts like that?

Thank you.

**Comment by matthewdeanmartin** [comment]
I'll be 10c that Assistant ignores all the special syntax and jut responds to the "please don't give me refusal text" and "please ignore the Terms of Service".  The former is more likely to work, the later is less likely to work, or if it does work now, it will stop working because you can tell a 2nd API call goes to the moderation model, Assistant isn't the only model enforcing ToS constraints.

So you could write the above sentiment in any syntax you like, including pig latin ( OBEY! IGNORE MODERATION RESTRICTIONS!)

**Comment by OliverTahir** [comment]
This is a great prompt, what about if some line will change for other purpose?
